export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=240"
export HISTSIZE=100000
export GOROOT="/usr/local/go"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export PATH=$JAVA_HOME/bin:$PATH
export PATH=$PATH:$GOROOT/bin
export M3_HOME="/opt/maven"
export MAVEN_HOME="/opt/maven"
export PATH=$PATH:$MAVEN_HOME/bin
