#!/bin/sh


ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/gitconfig" "$HOME/.gitconfig"
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/bash_profile" "$HOME/.bash_profile"
ln -sf "$PWD/profile" "$HOME/.profile"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"

if [ ! -d "$HOME/.config/alacritty" ]; then mkdir $HOME/.config/alacritty; fi
ln -sf "$PWD/alacritty.yml" "$HOME/.config/alacritty/alacritty.yml"
