#!/bin/sh


if ! [ -x "$(command -v mvn)" ]; then

  cd $(mktemp -d)
  echo $(pwd)
  wget https://downloads.apache.org/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz -P $(pwd)
  echo "Coping"
  tar xf apache-maven-*.tar.gz -C .
  rm apache-maven-*.tar.gz
  mv apache-maven-* maven
  
  sudo cp -rfl maven/ /opt/
  rm -rf maven

else
  echo 'maven already installed'
fi


